In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('house_price_regression_dataset.csv')
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [4]:
df.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,2.990000,1.973000,1986.550000,2.778087,1.022000,5.615000,6.188610e+05
std,1255.514921,1.427564,0.820332,20.632916,1.297903,0.814973,2.887059,2.535681e+05
min,503.000000,1.000000,1.000000,1950.000000,0.506058,0.000000,1.000000,1.116269e+05
25%,1749.500000,2.000000,1.000000,1969.000000,1.665946,0.000000,3.000000,4.016482e+05
50%,2862.500000,3.000000,2.000000,1986.000000,2.809740,1.000000,6.000000,6.282673e+05
75%,3849.500000,4.000000,3.000000,2004.250000,3.923317,2.000000,8.000000,8.271413e+05
max,4999.000000,5.000000,3.000000,2022.000000,4.989303,2.000000,10.000000,1.108237e+06

In [28]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

scaled_df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,0.190614,0.25,0.0,0.430556,0.020873,0.0,0.444444,0.151269
1,0.838301,0.50,1.0,0.916667,0.947295,0.5,0.555556,0.876606
2,0.687055,0.00,0.5,0.916667,0.697880,0.0,0.888889,0.668617
3,0.102980,0.00,0.5,0.375000,0.496205,0.5,0.777778,0.118474
4,0.983763,0.25,0.0,0.597222,0.935263,0.0,0.777778,0.933278

In [6]:
scaled_df.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.514329,0.497500,0.486500,0.507639,0.506782,0.511000,0.512778,0.508960
std,0.279252,0.356891,0.410166,0.286568,0.289501,0.407486,0.320784,0.254431
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.277246,0.250000,0.000000,0.263889,0.258716,0.000000,0.222222,0.291008
50%,0.524800,0.500000,0.500000,0.500000,0.513843,0.500000,0.555556,0.518398
75%,0.744328,0.750000,1.000000,0.753472,0.762229,1.000000,0.777778,0.717948
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
x = scaled_df.drop(columns=['House_Price'])
y = scaled_df['House_Price']
print(x)

     Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0          0.190614          0.25            0.0    0.430556  0.020873
1          0.838301          0.50            1.0    0.916667  0.947295
2          0.687055          0.00            0.5    0.916667  0.697880
3          0.102980          0.00            0.5    0.375000  0.496205
4          0.983763          0.25            0.0    0.597222  0.935263
..              ...           ...            ...         ...       ...
995        0.613434          0.75            0.0    0.388889  0.370056
996        0.595196          0.00            0.5    0.680556  0.551178
997        0.467749          0.75            0.5    0.166667  0.791616
998        0.938612          1.00            0.5    0.000000  0.317820
999        0.614991          0.75            0.5    0.458333  0.580547

     Garage_Size  Neighborhood_Quality
0            0.0              0.444444
1            0.5              0.555556
2            0.0              0.888889
3            0.5              0.777778
4            0.0              0.777778
..           ...                   ...
995          1.0              1.000000
996          0.5              1.000000
997          0.0              0.111111
998          0.0              0.666667
999          1.0              0.111111

[1000 rows x 7 columns]

In [8]:
x.value_counts()

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  Garage_Size  Neighborhood_Quality
0.000000        1.00          0.5            0.944444    0.193823  0.0          0.888889                1
0.681940        0.50          1.0            0.208333    0.476114  1.0          0.777778                1
0.670819        1.00          1.0            0.222222    0.781552  0.0          1.000000                1
0.673265        0.75          0.0            0.736111    0.126901  0.5          0.555556                1
0.673488        0.75          1.0            0.680556    0.287730  1.0          0.888889                1
                                                                                                       ..
0.372553        0.00          0.5            0.875000    0.132799  0.5          1.000000                1
0.372776        0.00          0.5            0.375000    0.279109  0.0          0.000000                1
0.372998        0.25          1.0            0.958333    0.239535  0.5          0.444444                1
0.373443        0.25          0.0            0.236111    0.014531  0.5          0.111111                1
1.000000        1.00          0.0            0.027778    0.927153  1.0          0.444444                1
Name: count, Length: 1000, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [10]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 7)
(200, 7)
(800,)
(200,)

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
model.coef_

array([9.00630864e-01, 4.03932537e-02, 1.60463837e-02, 7.13162793e-02,
       6.66402289e-02, 1.02067418e-02, 4.18148534e-04])

In [14]:
model.intercept_

np.float64(-0.05738814389144686)

In [15]:
Ypred = model.predict(x_test)

In [16]:
New = x_test
New['House_Price'] = y_test
New['pred_House_Price'] = Ypred

In [17]:
New

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price,pred_House_Price
233,0.689724,0.00,0.5,0.222222,0.643628,0.0,0.222222,0.630798,0.630654
943,0.731762,0.00,0.0,0.527778,0.997050,0.0,0.111111,0.695180,0.705788
521,0.780472,0.50,0.0,0.916667,0.355108,0.5,0.444444,0.792059,0.760052
613,0.301379,0.00,0.0,0.638889,0.901270,1.0,0.777778,0.323133,0.330199
525,0.796486,0.50,1.0,0.111111,0.582239,1.0,0.777778,0.748924,0.753451
...,...,...,...,...,...,...,...,...,...
7,0.648577,0.00,0.0,0.305556,0.512848,0.5,0.000000,0.593799,0.587811
332,0.025133,0.25,1.0,0.208333,0.659191,0.5,0.666667,0.069001,0.055561
934,0.750222,0.00,0.0,0.333333,0.695899,0.0,0.444444,0.684016,0.688618
167,0.796041,0.50,1.0,0.319444,0.079171,1.0,0.555556,0.748115,0.734290
459,0.162144,0.75,1.0,0.194444,0.339689,1.0,0.888889,0.186273,0.182068

In [18]:
New.to_csv("House_Price_ans.csv")

In [19]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, root_mean_squared_error

In [20]:
print(mean_squared_error(y_test,Ypred))

0.00010923759241106664

In [21]:
print(mean_absolute_error(y_test,Ypred))

0.008159108480046537

In [22]:
print(root_mean_squared_error(y_test,Ypred))

0.010451678927859706

In [23]:
print(mean_absolute_percentage_error(y_test,Ypred))

0.04066526666824519

In [24]:
from sklearn.metrics import r2_score

In [25]:
print(r2_score(y_test,Ypred))

0.9984321707895595