In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
df = pd.read_csv('Bangalore.csv')
df

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6202,5364000,590,Chandapura,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6203,8716000,1179,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6204,7373000,1143,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6205,4985000,1680,Kasavanahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6206,10900000,1162,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [72]:
print(f"DataFrame Info:\n{df.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6207 entries, 0 to 6206
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                6207 non-null   int64
 1   Area                 6207 non-null   int64
 2   Location             6207 non-null   object
 3   No. of Bedrooms      6207 non-null   int64
 4   Resale               6207 non-null   int64
 5   MaintenanceStaff     6207 non-null   int64
 6   Gymnasium            6207 non-null   int64
 7   SwimmingPool         6207 non-null   int64
 8   LandscapedGardens    6207 non-null   int64
 9   JoggingTrack         6207 non-null   int64
 10  RainWaterHarvesting  6207 non-null   int64
 11  IndoorGames          6207 non-null   int64
 12  ShoppingMall         6207 non-null   int64
 13  Intercom             6207 non-null   int64
 14  SportsFacility       6207 non-null   int64
 15  ATM                  6207 non-null   int64
 16  ClubHouse            6207 non-null   int64
 17  School               6207 non-null   int64
 18  24X7Security         6207 non-null   int64
 19  PowerBackup          6207 non-null   int64
 20  CarParking           6207 non-null   int64
 21  StaffQuarter         6207 non-null   int64
 22  Cafeteria            6207 non-null   int64
 23  MultipurposeRoom     6207 non-null   int64
 24  Hospital             6207 non-null   int64
 25  WashingMachine       6207 non-null   int64
 26  Gasconnection        6207 non-null   int64
 27  AC                   6207 non-null   int64
 28  Wifi                 6207 non-null   int64
 29  Children'splayarea   6207 non-null   int64
 30  LiftAvailable        6207 non-null   int64
 31  BED                  6207 non-null   int64
 32  VaastuCompliant      6207 non-null   int64
 33  Microwave            6207 non-null   int64
 34  GolfCourse           6207 non-null   int64
 35  TV                   6207 non-null   int64
 36  DiningTable          6207 non-null   int64
 37  Sofa                 6207 non-null   int64
 38  Wardrobe             6207 non-null   int64
 39  Stadium              6207 non-null   int64
dtypes: int64(39), object(1)
memory usage: 1.9+ MB
DataFrame Info:
None

In [73]:
df.isnull().sum()

Price                  0
Area                   0
Location               0
No. of Bedrooms        0
Resale                 0
MaintenanceStaff       0
Gymnasium              0
SwimmingPool           0
LandscapedGardens      0
JoggingTrack           0
RainWaterHarvesting    0
IndoorGames            0
ShoppingMall           0
Intercom               0
SportsFacility         0
ATM                    0
ClubHouse              0
School                 0
24X7Security           0
PowerBackup            0
CarParking             0
StaffQuarter           0
Cafeteria              0
MultipurposeRoom       0
Hospital               0
WashingMachine         0
Gasconnection          0
AC                     0
Wifi                   0
Children'splayarea     0
LiftAvailable          0
BED                    0
VaastuCompliant        0
Microwave              0
GolfCourse             0
TV                     0
DiningTable            0
Sofa                   0
Wardrobe               0
Stadium                0
dtype: int64

In [74]:
print(f"\nDataFrame Description:\n{df.describe()}")

DataFrame Description:
              Price         Area  No. of Bedrooms       Resale  \
count  6.207000e+03  6207.000000      6207.000000  6207.000000
mean   1.058510e+07  1526.094248         2.556952     0.078782
std    1.410943e+07   764.845609         0.694300     0.269420
min    2.000000e+06   415.000000         1.000000     0.000000
25%    5.000000e+06  1110.000000         2.000000     0.000000
50%    7.368000e+06  1340.000000         3.000000     0.000000
75%    1.070000e+07  1662.500000         3.000000     0.000000
max    3.000000e+08  9900.000000         7.000000     1.000000

       MaintenanceStaff    Gymnasium  SwimmingPool  LandscapedGardens  \
count       6207.000000  6207.000000   6207.000000        6207.000000
mean           6.208797     6.461576      6.436121           6.382471
std            4.126883     3.752421      3.792567           3.875271
min            0.000000     0.000000      0.000000           0.000000
25%            0.000000     1.000000      1.000000           1.000000
50%            9.000000     9.000000      9.000000           9.000000
75%            9.000000     9.000000      9.000000           9.000000
max            9.000000     9.000000      9.000000           9.000000

       JoggingTrack  RainWaterHarvesting  ...  LiftAvailable          BED  \
count   6207.000000          6207.000000  ...    6207.000000  6207.000000
mean       6.396649             6.373933  ...       6.438537     6.211052
std        3.853661             3.888204  ...       3.788782     4.123761
min        0.000000             0.000000  ...       0.000000     0.000000
25%        1.000000             1.000000  ...       1.000000     0.000000
50%        9.000000             9.000000  ...       9.000000     9.000000
75%        9.000000             9.000000  ...       9.000000     9.000000
max        9.000000             9.000000  ...       9.000000     9.000000

       VaastuCompliant    Microwave   GolfCourse           TV  DiningTable  \
count      6207.000000  6207.000000  6207.000000  6207.000000  6207.000000
mean          6.311100     6.210569     6.181569     6.210569     6.210569
std           3.981513     4.124430     4.164294     4.124430     4.124430
min           0.000000     0.000000     0.000000     0.000000     0.000000
25%           1.000000     0.000000     0.000000     0.000000     0.000000
50%           9.000000     9.000000     9.000000     9.000000     9.000000
75%           9.000000     9.000000     9.000000     9.000000     9.000000
max           9.000000     9.000000     9.000000     9.000000     9.000000

              Sofa     Wardrobe      Stadium
count  6207.000000  6207.000000  6207.000000
mean      6.210569     6.171097     6.210569
std       4.124430     4.178546     4.124430
min       0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000
50%       9.000000     9.000000     9.000000
75%       9.000000     9.000000     9.000000
max       9.000000     9.000000     9.000000

[8 rows x 39 columns]

In [75]:
df.shape

(6207, 40)

In [76]:
df.duplicated().sum()

np.int64(686)

In [77]:
df = df.drop_duplicates()

In [78]:

df.columns = df.columns.str.lower()

In [79]:
df.columns

Index(['price', 'area', 'location', 'no. of bedrooms', 'resale',
       'maintenancestaff', 'gymnasium', 'swimmingpool', 'landscapedgardens',
       'joggingtrack', 'rainwaterharvesting', 'indoorgames', 'shoppingmall',
       'intercom', 'sportsfacility', 'atm', 'clubhouse', 'school',
       '24x7security', 'powerbackup', 'carparking', 'staffquarter',
       'cafeteria', 'multipurposeroom', 'hospital', 'washingmachine',
       'gasconnection', 'ac', 'wifi', 'children'splayarea', 'liftavailable',
       'bed', 'vaastucompliant', 'microwave', 'golfcourse', 'tv',
       'diningtable', 'sofa', 'wardrobe', 'stadium'],
      dtype='object')

In [80]:
features = ['no. of bedrooms','gymnasium', 'swimmingpool', 'landscapedgardens',
'joggingtrack','indoorgames','clubhouse','securitystaff','powerbackup','carparking','children\'s playarea', 'liftavailable']

In [ ]:
df =df.drop([ 'rainwaterharvesting', 'shoppingmall',
        'sportsfacility', 'atm', 'school', 'hospital', 'multipurposeroom', 'staffquarter', 'microwave', 'golfcourse', 'tv',
       'diningtable', 'sofa', 'wardrobe', 'stadium','cafeteria','washingmachine','gasconnection','maintenancestaff'], axis=1)

In [52]:
pd.get_dummies(df['location'])

,5th Phase,5th Stage BEML Layout,5th Stage Raja Rajeshwari Nagar,6th phase jp nagar,7th Phase JP Nagar,8th Phase JP Nagar,AECS Layout A Block Singasandra,AGS Layout Arehalli,Abbigere,Adugodi,...,White Field,Whitefield,Whitefield Hope Farm Junction,Whitefield Road,Yelahanka,Yelahanka New Town,Yerthiganahalli,Yeshwantpur,hebbal kempapura,sarjapura attibele road
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6205,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6206,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [85]:
df.tail(30)

,price,area,location,no. of bedrooms,resale,maintenancestaff,gymnasium,swimmingpool,landscapedgardens,joggingtrack,...,clubhouse,24x7security,powerbackup,carparking,ac,wifi,children'splayarea,liftavailable,bed,vaastucompliant
6177,11900000,2204,Thanisandra,4,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6178,8033000,1060,Hosa Road Electronic City,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6179,8877000,1060,Kudlu Gate,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6180,3030000,1060,Hosa Road Junction,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6181,3950000,1690,Doddaballapur,4,1,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6182,5000000,3000,Bhoopasandra,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6183,11900000,1598,Marathahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6184,6200000,1341,Narayanapura on Hennur Main Road,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6185,2310000,1482,Narayanapura on Hennur Main Road,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6186,4057000,1010,Kachanayakanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6187,3700000,883,Mysore Road,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6188,12500000,888,Kumbalgodu,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6189,3902000,1887,Bilekahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6190,2800000,1320,Seegehalli Road,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6191,9500000,660,Chandapura,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6192,11100000,1400,Sarjapur Attibele,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6193,11200000,920,Channasandra Layout,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6194,6251000,1763,Ramamurthy Nagar,3,1,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6195,3232000,985,Chandapura Anekal Road,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6196,2150000,873,Chandapura,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6197,5305000,1500,Budigere,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6198,5143000,2145,Bagaluru Near Yelahanka,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6199,7559999,2064,Sarjapur Road,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6200,5229000,1115,HAL,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6201,8545000,1010,Bommasandra,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6202,5364000,590,Chandapura,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6203,8716000,1179,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6204,7373000,1143,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6205,4985000,1680,Kasavanahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6206,10900000,1162,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [54]:
df.shape

(5521, 40)

In [68]:
features

['no. of bedrooms',
 'gymnasium',
 'swimmingpool',
 'landscapedgardens',
 'joggingtrack',
 'indoorgames',
 'clubhouse',
 'securitystaff',
 'powerbackup',
 'carparking',
 "children's playarea",
 'liftavailable']

In [90]:
df['gymnasium'].unique()

array([1, 0, 9])

In [91]:
df['gymnasium'].value_counts()

gymnasium
9    3904
1    1486
0     131
Name: count, dtype: int64

In [92]:
df[df['maintenancestaff'] == 9].head()

,price,area,location,no. of bedrooms,resale,maintenancestaff,gymnasium,swimmingpool,landscapedgardens,joggingtrack,...,clubhouse,24x7security,powerbackup,carparking,ac,wifi,children'splayarea,liftavailable,bed,vaastucompliant
1951,6884999,1215,Varthur,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
1952,7959999,1290,Electronic City Phase 2,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
1953,7975000,1505,Electronic City Phase 2,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
1954,7625000,1535,Electronic City Phase 2,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
1955,5760000,1465,Electronic City Phase 2,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9